# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy org website to Azure Web App - OrgWebApp

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    permissions:
      id-token: write
      contents: read
    
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
        
      - name: Build the site in the jekyll/builder container
        run: |
          # docker run --rm \
          #  --volume="$PWD:/srv/jekyll" \
          #  jekyll/builder:stable /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build"
            
          docker run \
            -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:stable /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
          
      - name: Test site      
        run: |
          file ${{ github.workspace }}/_site/assets/OASIS.png
          
      - name: Another test site      
        run: |
          file ${{ github.workspace }}/assets/OASIS.png

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          // creds: '${{ secrets.ORGWEBAPP_PUBLISH_CREDENTIALS }}'
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'OrgWebApp'
          slot-name: 'Production'
          package: ${{ github.workspace }}/_site
